language: php
php:
  - '5.6'
dist: xenial
notifications:
  email: false
jobs:
  include:
    - stage: build
      php:
        - '5.6'
      script:
        - curl -OS http://couscous.io/couscous.phar
        - chmod +x couscous.phar
        - sudo mv couscous.phar /usr/local/bin/couscous
        - couscous generate
    - stage: release
      php:
        - '5.6'
      script:
        - curl -OS http://couscous.io/couscous.phar
        - chmod +x couscous.phar
        - sudo mv couscous.phar /usr/local/bin/couscous
        - couscous generate
        - pip install --user awscli
        - aws s3 sync .couscous/generated/ "s3://pelias.io-website/"
      if: (branch = master) AND ( type = push )
